name: Deploy
on:
  workflow_call:
    inputs:
      tag:
        description: "The tag to deploy"
        required: true
        type: string
      stack:
        description: "The stack to deploy to"
        required: true
        type: string
jobs:
  do_deploy:
    env:
      GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      DEPLOY_REPO: ${{ github.repository }}
      DEPLOY_OWNER: merryfield
      DEPLOY_BRANCH: ${{ github.ref }}
      DEPLOY_SHA1: ${{ github.sha }}
      DEPLOY_RUN_ID: ${{ github.run_id }}
      AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}/crm-service
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
      NEW_RELIC_API_KEY_PROD: ${{ secrets.NEW_RELIC_API_KEY_PROD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      JOB_NAME: Deploy ${{github.event.inputs.tag}} to ${{github.event.inputs.stack}}
    runs-on: ubuntu-latest
    container: 
      image: docker.pkg.github.com/merryfield/deployment/deployment:latest
      credentials:
        username: ${{ secrets.DEPLOY_GITHUB_USER }}
        password: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
    name: Deploy ${{github.event.inputs.tag}} to ${{github.event.inputs.stack}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: act10ns/slack@v1
      with:
        status: starting
        config: .github/config/slack.yml
    - name: Deploy
      run: |
        node /opt/deployment/index.js ${{ github.event.inputs.tag }} ${{ github.event.inputs.stack }}
    - name: Notify
      uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        config: .github/config/slack.yml
      if: always()
