name: Deploy
on:
  workflow_call:
    inputs:
      tag:
        description: "The tag to deploy"
        required: true
        type: string
      stack:
        description: "The stack to deploy to"
        required: true
        type: string
    secrets:
      DEPLOY_GITHUB_TOKEN:
        required: true
      AWS_ECR_URI:
        required: true
      AWS_ACCOUNT_ID: 
        required: true
      AWS_ACCESS_KEY_ID: 
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      NEW_RELIC_API_KEY:
        required: true
      NEW_RELIC_API_KEY_PROD:
        required: true
      SLACK_WEBHOOK_URL: 
        required: true
jobs:
  do_deploy:
    env:
      DEPLOY_GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      DEPLOY_REPO: ${{github.repository}}
      DEPLOY_OWNER: merryfield
      DEPLOY_BRANCH: ${{github.ref}}
      DEPLOY_SHA1: ${{github.sha}}
      DEPLOY_RUN_ID: ${{github.run_id}}
      AWS_ECR_URI: ${{secrets.AWS_ECR_URI}}
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      NEW_RELIC_API_KEY: ${{secrets.NEW_RELIC_API_KEY}}
      NEW_RELIC_API_KEY_PROD: ${{secrets.NEW_RELIC_API_KEY_PROD}}
      SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
      JOB_NAME: Deploy ${{inputs.tag}} to ${{inputs.stack}}
      WORKFLOW_RUN_URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
      REF_URL: ${{github.server_url}}/${{gihub.repository}}/commits/${{github.head_ref || github.ref?.replace('refs/heads/', '')}}
    runs-on: ubuntu-latest
#    container: 
#      image: docker.pkg.github.com/merryfield/deployment/deployment:latest
#      credentials:
#        username: ${{ secrets.DEPLOY_GITHUB_USER }}
#        password: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
    name: ${{inputs.tag}} to ${{inputs.stack}}
    steps:
    - name: Diag
      run: env
    - name: Checkout
      uses: actions/checkout@v2
    - name: Notify Start
      uses: act10ns/slack@v1
      with:
        status: starting
        message: |
          *<${{env.WORKFLOW_RUN_URL}}|_${{env.JOB_NAME}}_ : _STARTING_>*
          <${{env.REF_URL}}|`${{github.ref}}`>
#        config: .github/config/slack.yml
    - name: Deploy
      run: |
        node /opt/deployment/index.js ${{inputs.tag}} ${{inputs.stack}}
    - name: Notify Finish
      uses: act10ns/slack@v1
      with:
        status: ${{job.status}}
        config: .github/config/slack.yml
      if: always()
